### ISSUE TITLE
Image not found?

### ISSUE THREAD

**Issue by lspoor** [Slicejack/bojler#51]
So running `npm run gulp dev` to watch my files. I have created an `assets` folder within `public` and put one image in, I have referenced to this in my HTML file with
```
<img src="assets/f1-logo.gif" alt="Formula One Autocentres" width="562" height="32" />
```

The image appears in the browser fine but I'm getting errors in the terminal..

```
 Error: The file /Users/Luke/Desktop/bojler/assets/f1-logo.gif was not found!
    at DataURI.encodeSync (/Users/Luke/Desktop/bojler/node_modules/datauri/api.js:102:11)
    at new DataURI (/Users/Luke/Desktop/bojler/node_modules/datauri/module.js:24:34)
    at Object.util.getFileReplacement (/Users/Luke/Desktop/bojler/node_modules/web-resource-inliner/src/util.js:184:24)
    at Object.replaceImg (/Users/Luke/Desktop/bojler/node_modules/web-resource-inliner/src/html.js:121:16)
    at /Users/Luke/Desktop/bojler/node_modules/async/dist/async.js:3853:24
    at eachOfArrayLike (/Users/Luke/Desktop/bojler/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/Luke/Desktop/bojler/node_modules/async/dist/async.js:1051:5)
    at _parallel (/Users/Luke/Desktop/bojler/node_modules/async/dist/async.js:3852:5)
    at parallelLimit (/Users/Luke/Desktop/bojler/node_modules/async/dist/async.js:3935:5)
    at Object.module.exports [as html] (/Users/Luke/Desktop/bojler/node_modules/web-resource-inliner/src/html.js:254:5)
```

**Comment by alenvuletic** [comment]
@lspoor This should be fixed. Please download latest release (v2.1.1).

Thanks :)
